### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by trungkstn** [SamsungARTIK/ubuntu-build-service#1]
When i rung
```
cd xenial-armhf-artik530
./configure
make
```
I get error: 
Unable to locate package artik-ubuntu-meta-base, artik-ubuntu-meta-network ...
Do you know how to fix this issue?

**Comment by cometzero** [comment]
Hi,

All artik packages could be downloaded from artik platform source list[1].
Could you show me full log when you tried to run 'make'?

[1]: https://github.com/SamsungARTIK/ubuntu-build-service/blob/A530_os_3.0.0/artik-common/artik-platform-artik530-sources.list

**Comment by trungkstn** [comment]
I get error

> Err:1 http://localhost:8000  InRelease
>   Unable to connect to localhost:8000: [IP: 127.0.0.1 8000]
> 

and

> W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease  Could not connect to 12.26.226.2:8080 (12.26.226.2), connection timed out
> W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/xenial-security/InRelease  Unable to connect to 12.26.226.2:8080:
> W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/xenial-updates/InRelease  Unable to connect to 12.26.226.2:8080:
> W: Failed to fetch http://localhost:8000/InRelease  Unable to connect to localhost:8000: [IP: 127.0.0.1 8000]
> W: Failed to fetch http://repo.artik.cloud/artik/bin/pub/artik-platform/ubuntu/artik530/dists/A530_os_3.0.0/InRelease  Could not connect to 12.26.226.2:8080 (12.26.226.2), connection timed out
> W: Failed to fetch http://repo.artik.cloud/artik/bin/pub/artik-platform/ubuntu/artik530/dists/updates/InRelease  Unable to connect to 12.26.226.2:8080:

**Comment by cometzero** [comment]
@trungkstn Hi, I've updated the A530_os_3.0.0 and A710_os_3.0.0 branches. It was caused from invalid proxy information by the manual merge.
Please pull the branch to the latest.
