### ISSUE TITLE
wrong --bootstrap-qemu-static

### ISSUE THREAD

**Issue by phuclm** [SamsungARTIK/ubuntu-build-service#2]
https://github.com/SamsungARTIK/ubuntu-build-service/blob/421d64061472c4070450bbe058cf043873085066/xenial-armhf-artik530/configure#L27
 need change to --bootstrap-qemu-static /var/lib/schroot/chroots/xenial-amd64-armhf/usr/bin/qemu-arm-static

**Comment by cometzero** [comment]
Hi @phuclm ,
You're right. However, the live-build can work with ubuntu's official qemu-arm-static version.
The reason why we picked the custom(up-to-date) version qemu, the iotivity build has a problem during build. However, there was no problem to generate a rootfs tarball using the live-build.

**Comment by phuclm** [comment]
@cometzero no, for now, i still can't build rootfs tarbar, here is error
![build_rootfs_error](https://user-images.githubusercontent.com/25562724/34973483-59e48dea-faba-11e7-99ef-7aef1d7fa96f.PNG)

**Comment by cometzero** [comment]
According to your log, you still used the  /var/lib/schroot/chroots/xenial-amd64-armhf/usr/bin/qemu-arm-static. Please revert the change and check whether you installed the qemu-user-static package in your system.

**Comment by phuclm** [comment]
@cometzero in /usr/bin don't have qemu-arm-static
![rollback_error](https://user-images.githubusercontent.com/25562724/34974349-0fb3f1de-fabf-11e7-9c53-43f0201defb3.PNG)

**Comment by cometzero** [comment]
Please install "qemu-user-static" package before you run the "make"
$ sudo apt-get install qemu-user-static
I hope it could help your problem. Sorry for your inconvenience.
I'll update the guide soon.

**Comment by phuclm** [comment]
@cometzero so, /var/lib/schroot/chroots/xenial-amd64-armhf/usr/bin/qemu-arm-static will just used for **sbuild** when build deb packages?

**Comment by phuclm** [comment]
@cometzero please update the guide soon, qemu-arm-static was downloaded by follow this guide seem to be used for fedora, not ubuntu,...
this issue about correct location of qemu-arm-static, so i think i can close it now.
