### ISSUE TITLE
generate rootfs tarball

### ISSUE THREAD

**Issue by trungkstn** [SamsungARTIK/ubuntu-build-service#3]
> Build output The rootfs tarball will be generated in each directory as "xenial-{artik_module}-YYMMDD-1.tar.gz". You can use the tarball for deploying artik image from build-artik.

I cloned new update and followed new guide and. I don't get error I asked but I don't see file *.tar.gz in directory. Also i see error **cannot stat 'chroot/chroot': No such file or directory**

> P: Begin building root filesystem image...
> mv: cannot stat 'chroot/chroot': No such file or directory
> P: Begin unmounting filesystems...
> P: Saving caches...
> if [ -f binary-tar.tar.gz ]; then \
> 	mkdir tmp_rootfs; \
> 	cd tmp_rootfs; sudo tar xf ../binary-tar.tar.gz ; \
> 	sudo mv binary/* .; sudo rmdir binary; \
> 	sudo tar zcf ../binary-tar.tar.gz *; \
> 	cd ..; sudo rm -rf tmp_rootfs; \
> 	tar -jcf xenial-artik530-`date +%Y%m%d`-1.config.tar.bz2 auto/ config/ configure; \
> 	sudo mv binary.contents xenial-artik530-`date +%Y%m%d`-1.contents; \
> 	sudo mv chroot.packages.live xenial-artik530-`date +%Y%m%d`-1.packages; \
> 	sudo mv binary-tar.tar.gz xenial-artik530-`date +%Y%m%d`-1.tar.gz; \
> 	md5sum xenial-artik530-`date +%Y%m%d`-1.build-log.txt xenial-artik530-`date +%Y%m%d`-1.config.tar.bz2 xenial-artik530-`date +%Y%m%d`-1.contents xenial-artik530-`date +%Y%m%d`-1.packages xenial-artik530-`date +%Y%m%d`-1.tar.gz > xenial-artik530-`date +%Y%m%d`-1.md5sums.txt; \
> 	sha1sum xenial-artik530-`date +%Y%m%d`-1.build-log.txt xenial-artik530-`date +%Y%m%d`-1.config.tar.bz2 xenial-artik530-`date +%Y%m%d`-1.contents xenial-artik530-`date +%Y%m%d`-1.packages xenial-artik530-`date +%Y%m%d`-1.tar.gz > xenial-artik530-`date +%Y%m%d`-1.sha1sums.txt; \
> fi

**Comment by cometzero** [comment]
Hi @trungkstn ,
It seemed the mismatch version of the libdrm package. Since we released the custom libdrm package, the ubuntu's libdrm has been upgraded to 2.4.83 version. So, I've updated the A530_os_3.0.0 branch to address this problem. Could you make the rootfs once again?

$ git pull
$ cd xenial-armhf-artik530
$ make clean
$ ./configure
$ make

**Comment by trungkstn** [comment]
Thank you. I done.
